In [1]:
import pandas as pd
import numpy as np

print("Proyecto Mundial 2026 iniciado")

Proyecto Mundial 2026 iniciado

In [2]:
matches = pd.read_csv("../data/raw/worldcup_db/data-csv/matches.csv"
)

In [3]:
matches.head()

,key_id,tournament_id,tournament_name,match_id,match_name,stage_name,group_name,group_stage,knockout_stage,replayed,...,away_team_score_margin,extra_time,penalty_shootout,score_penalties,home_team_score_penalties,away_team_score_penalties,result,home_team_win,away_team_win,draw
0,1,WC-1930,1930 FIFA Men's World Cup,M-1930-01,France vs Mexico,group stage,Group 1,1,0,0,...,-3,0,0,0-0,0,0,home team win,1,0,0
1,2,WC-1930,1930 FIFA Men's World Cup,M-1930-02,United States vs Belgium,group stage,Group 4,1,0,0,...,-3,0,0,0-0,0,0,home team win,1,0,0
2,3,WC-1930,1930 FIFA Men's World Cup,M-1930-03,Yugoslavia vs Brazil,group stage,Group 2,1,0,0,...,-1,0,0,0-0,0,0,home team win,1,0,0
3,4,WC-1930,1930 FIFA Men's World Cup,M-1930-04,Romania vs Peru,group stage,Group 3,1,0,0,...,-2,0,0,0-0,0,0,home team win,1,0,0
4,5,WC-1930,1930 FIFA Men's World Cup,M-1930-05,Argentina vs France,group stage,Group 1,1,0,0,...,-1,0,0,0-0,0,0,home team win,1,0,0

In [5]:
matches.shape

(1248, 37)

In [6]:
matches.info()

<class 'pandas.DataFrame'>
RangeIndex: 1248 entries, 0 to 1247
Data columns (total 37 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   key_id                     1248 non-null   int64
 1   tournament_id              1248 non-null   str
 2   tournament_name            1248 non-null   str
 3   match_id                   1248 non-null   str
 4   match_name                 1248 non-null   str
 5   stage_name                 1248 non-null   str
 6   group_name                 1248 non-null   str
 7   group_stage                1248 non-null   int64
 8   knockout_stage             1248 non-null   int64
 9   replayed                   1248 non-null   int64
 10  replay                     1248 non-null   int64
 11  match_date                 1248 non-null   str
 12  match_time                 1248 non-null   str
 13  stadium_id                 1248 non-null   str
 14  stadium_name               1248 non-null   str
 15  city_name                  1248 non-null   str
 16  country_name               1248 non-null   str
 17  home_team_id               1248 non-null   str
 18  home_team_name             1248 non-null   str
 19  home_team_code             1248 non-null   str
 20  away_team_id               1248 non-null   str
 21  away_team_name             1248 non-null   str
 22  away_team_code             1248 non-null   str
 23  score                      1248 non-null   str
 24  home_team_score            1248 non-null   int64
 25  away_team_score            1248 non-null   int64
 26  home_team_score_margin     1248 non-null   int64
 27  away_team_score_margin     1248 non-null   int64
 28  extra_time                 1248 non-null   int64
 29  penalty_shootout           1248 non-null   int64
 30  score_penalties            1248 non-null   str
 31  home_team_score_penalties  1248 non-null   int64
 32  away_team_score_penalties  1248 non-null   int64
 33  result                     1248 non-null   str
 34  home_team_win              1248 non-null   int64
 35  away_team_win              1248 non-null   int64
 36  draw                       1248 non-null   int64
dtypes: int64(16), str(21)
memory usage: 360.9 KB

In [7]:
players = pd.read_csv(
    "../data/raw/worldcup_db/data-csv/players.csv"
)

players.head()

,key_id,player_id,family_name,given_name,birth_date,female,goal_keeper,defender,midfielder,forward,count_tournaments,list_tournaments,player_wikipedia_link
0,1,P-35894,A'Court,Alan,1934-09-30,0,0,0,0,1,1,1958,https://en.wikipedia.org/wiki/Alan_A%27Court
1,2,P-29915,Aarønes,Ann Kristin,1973-01-19,1,0,0,1,1,2,"1995, 1999",https://en.wikipedia.org/wiki/Ann_Kristin_Aar%...
2,3,P-03484,Aaronson,Brenden,2000-10-22,0,0,0,0,1,1,2022,https://en.wikipedia.org/wiki/Brenden_Aaronson
3,4,P-04189,Abadzhiev,Stefan,1934-07-03,0,0,0,0,1,1,1966,https://en.wikipedia.org/wiki/Stefan_Abadzhiev
4,5,P-03523,Abalo,Jean-Paul,1975-06-26,0,0,1,0,0,1,2006,https://en.wikipedia.org/wiki/Jean-Paul_Abalo

In [8]:
players.columns.tolist()

['key_id',
 'player_id',
 'family_name',
 'given_name',
 'birth_date',
 'female',
 'goal_keeper',
 'defender',
 'midfielder',
 'forward',
 'count_tournaments',
 'list_tournaments',
 'player_wikipedia_link']

In [9]:
players.info()

<class 'pandas.DataFrame'>
RangeIndex: 10401 entries, 0 to 10400
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   key_id                 10401 non-null  int64
 1   player_id              10401 non-null  str
 2   family_name            10401 non-null  str
 3   given_name             10401 non-null  str
 4   birth_date             10400 non-null  str
 5   female                 10401 non-null  int64
 6   goal_keeper            10401 non-null  int64
 7   defender               10401 non-null  int64
 8   midfielder             10401 non-null  int64
 9   forward                10401 non-null  int64
 10  count_tournaments      10401 non-null  int64
 11  list_tournaments       10401 non-null  str
 12  player_wikipedia_link  10401 non-null  str
dtypes: int64(7), str(6)
memory usage: 1.0 MB

In [10]:
squads = pd.read_csv(
    "../data/raw/worldcup_db/data-csv/squads.csv"
)

squads.info()

<class 'pandas.DataFrame'>
RangeIndex: 13843 entries, 0 to 13842
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   key_id           13843 non-null  int64
 1   tournament_id    13843 non-null  str
 2   tournament_name  13843 non-null  str
 3   team_id          13843 non-null  str
 4   team_name        13843 non-null  str
 5   team_code        13843 non-null  str
 6   player_id        13843 non-null  str
 7   family_name      13843 non-null  str
 8   given_name       13843 non-null  str
 9   shirt_number     13843 non-null  int64
 10  position_name    13843 non-null  str
 11  position_code    13843 non-null  str
dtypes: int64(2), str(10)
memory usage: 1.3 MB

In [11]:
player_appearances = pd.read_csv(
    "../data/raw/worldcup_db/data-csv/player_appearances.csv"
)

player_appearances.info()

<class 'pandas.DataFrame'>
RangeIndex: 27432 entries, 0 to 27431
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   key_id           27432 non-null  int64
 1   tournament_id    27432 non-null  str
 2   tournament_name  27432 non-null  str
 3   match_id         27432 non-null  str
 4   match_name       27432 non-null  str
 5   match_date       27432 non-null  str
 6   stage_name       27432 non-null  str
 7   group_name       27432 non-null  str
 8   team_id          27432 non-null  str
 9   team_name        27432 non-null  str
 10  team_code        27432 non-null  str
 11  home_team        27432 non-null  int64
 12  away_team        27432 non-null  int64
 13  player_id        27432 non-null  str
 14  family_name      27432 non-null  str
 15  given_name       27432 non-null  str
 16  shirt_number     27432 non-null  int64
 17  position_name    27432 non-null  str
 18  position_code    27432 non-null  str
 19  starter          27432 non-null  int64
 20  substitute       27432 non-null  int64
dtypes: int64(6), str(15)
memory usage: 4.4 MB

In [12]:
import json

with open(
    "../data/raw/statsbomb/data/competitions.json",
    encoding="utf-8"
) as f:
    competitions = json.load(f)

len(competitions)

80

In [13]:
competitions[:5]

[{'competition_id': 9,
  'season_id': 281,
  'country_name': 'Germany',
  'competition_name': '1. Bundesliga',
  'competition_gender': 'male',
  'competition_youth': False,
  'competition_international': False,
  'season_name': '2023/2024',
  'match_updated': '2024-09-28T20:46:38.893391',
  'match_updated_360': '2025-11-15T23:17:41.827093',
  'match_available_360': '2025-11-15T23:17:41.827093',
  'match_available': '2024-09-28T20:46:38.893391'},
 {'competition_id': 9,
  'season_id': 27,
  'country_name': 'Germany',
  'competition_name': '1. Bundesliga',
  'competition_gender': 'male',
  'competition_youth': False,
  'competition_international': False,
  'season_name': '2015/2016',
  'match_updated': '2024-05-19T11:11:14.192381',
  'match_updated_360': None,
  'match_available_360': None,
  'match_available': '2024-05-19T11:11:14.192381'},
 {'competition_id': 1267,
  'season_id': 107,
  'country_name': 'Africa',
  'competition_name': 'African Cup of Nations',
  'competition_gender': 'male',
  'competition_youth': False,
  'competition_international': True,
  'season_name': '2023',
  'match_updated': '2026-05-12T21:18:08.827431',
  'match_updated_360': '2026-05-02T02:07:18.902396',
  'match_available_360': '2026-05-02T02:07:18.902396',
  'match_available': '2026-05-12T21:18:08.827431'},
 {'competition_id': 16,
  'season_id': 4,
  'country_name': 'Europe',
  'competition_name': 'Champions League',
  'competition_gender': 'male',
  'competition_youth': False,
  'competition_international': False,
  'season_name': '2018/2019',
  'match_updated': '2026-05-15T15:54:04.598614',
  'match_updated_360': '2021-06-13T16:17:31.694',
  'match_available_360': None,
  'match_available': '2026-05-15T15:54:04.598614'},
 {'competition_id': 16,
  'season_id': 1,
  'country_name': 'Europe',
  'competition_name': 'Champions League',
  'competition_gender': 'male',
  'competition_youth': False,
  'competition_international': False,
  'season_name': '2017/2018',
  'match_updated': '2024-02-13T02:35:28.134882',
  'match_updated_360': '2021-06-13T16:17:31.694',
  'match_available_360': None,
  'match_available': '2024-02-13T02:35:28.134882'}]

In [14]:
comp_df = pd.DataFrame(competitions)

comp_df[
    comp_df["competition_name"].str.contains(
        "World",
        case=False,
        na=False
    )
]

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
29,1470,274,International,FIFA U20 World Cup,male,True,True,1979,2024-02-13T14:20:59.825440,NaN,NaN,2024-02-13T14:20:59.825440
30,43,106,International,FIFA World Cup,male,False,True,2022,2026-05-04T01:48:57.914346,2026-05-04T01:53:40.309717,2026-05-04T01:53:40.309717,2026-05-04T01:48:57.914346
31,43,3,International,FIFA World Cup,male,False,True,2018,2026-05-15T15:48:12.789440,2021-06-13T16:17:31.694,NaN,2026-05-15T15:48:12.789440
32,43,55,International,FIFA World Cup,male,False,True,1990,2023-06-28T10:58:20.137929,2021-06-12T16:17:31.694,NaN,2023-06-28T10:58:20.137929
33,43,54,International,FIFA World Cup,male,False,True,1986,2026-05-04T01:30:23.212111,2021-06-13T16:17:31.694,NaN,2026-05-04T01:30:23.212111
34,43,51,International,FIFA World Cup,male,False,True,1974,2026-05-15T02:20:43.439689,2021-06-13T16:17:31.694,NaN,2026-05-15T02:20:43.439689
35,43,272,International,FIFA World Cup,male,False,True,1970,2026-05-04T02:09:10.916859,NaN,NaN,2026-05-04T02:09:10.916859
36,43,270,International,FIFA World Cup,male,False,True,1962,2026-05-04T02:05:35.653887,NaN,NaN,2026-05-04T02:05:35.653887
37,43,269,International,FIFA World Cup,male,False,True,1958,2026-05-04T02:02:41.853159,NaN,NaN,2026-05-04T02:02:41.853159
78,72,107,International,Women's World Cup,female,False,True,2023,2026-05-03T13:51:31.021141,2026-05-03T13:55:52.303219,2026-05-03T13:55:52.303219,2026-05-03T13:51:31.021141
79,72,30,International,Women's World Cup,female,False,True,2019,2026-05-15T15:31:40.299642,2021-06-13T16:17:31.694,NaN,2026-05-15T15:31:40.299642

In [15]:
import json
import pandas as pd

with open(
    "../data/raw/statsbomb/data/matches/43/106.json",
    encoding="utf-8"
) as f:
    wc2022_matches = json.load(f)

len(wc2022_matches)

64

In [16]:
pd.DataFrame(wc2022_matches).head()

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,metadata,match_week,competition_stage,stadium,referee
0,3857276,2022-12-01,15:00:00.000,"{'competition_id': 43, 'country_name': 'Intern...","{'season_id': 106, 'season_name': '2022'}","{'home_team_id': 1833, 'home_team_name': 'Cana...","{'away_team_id': 788, 'away_team_name': 'Moroc...",1,2,available,available,2026-05-04T01:46:04.664252,2026-05-04T01:50:33.318123,"{'data_version': '1.1.0', 'shot_fidelity_versi...",3,"{'id': 10, 'name': 'Group Stage'}","{'id': 1000838, 'name': 'Al Thumama Stadium', ...","{'id': 2638, 'name': 'Raphael Claus', 'country..."
1,3857271,2022-11-21,13:00:00.000,"{'competition_id': 43, 'country_name': 'Intern...","{'season_id': 106, 'season_name': '2022'}","{'home_team_id': 768, 'home_team_name': 'Engla...","{'away_team_id': 797, 'away_team_name': 'Iran'...",6,2,available,available,2026-05-04T01:40:47.671394,2026-05-04T01:43:30.216315,"{'data_version': '1.1.0', 'shot_fidelity_versi...",1,"{'id': 10, 'name': 'Group Stage'}","{'id': 1000253, 'name': 'Sheikh Khalifa Intern...","{'id': 2638, 'name': 'Raphael Claus', 'country..."
2,3857296,2022-12-01,15:00:00.000,"{'competition_id': 43, 'country_name': 'Intern...","{'season_id': 106, 'season_name': '2022'}","{'home_team_id': 785, 'home_team_name': 'Croat...","{'away_team_id': 782, 'away_team_name': 'Belgi...",0,0,available,available,2026-05-04T01:44:02.255386,2026-05-04T01:50:06.343225,"{'data_version': '1.1.0', 'shot_fidelity_versi...",3,"{'id': 10, 'name': 'Group Stage'}","{'id': 1000793, 'name': 'Ahmad bin Ali Stadium...","{'id': 8, 'name': 'Anthony Taylor', 'country':..."
3,3857274,2022-11-25,16:00:00.000,"{'competition_id': 43, 'country_name': 'Intern...","{'season_id': 106, 'season_name': '2022'}","{'home_team_id': 941, 'home_team_name': 'Nethe...","{'away_team_id': 3565, 'away_team_name': 'Ecua...",1,1,available,available,2026-05-04T01:43:00.444702,2026-05-04T01:50:07.646458,"{'data_version': '1.1.0', 'shot_fidelity_versi...",2,"{'id': 10, 'name': 'Group Stage'}","{'id': 1000253, 'name': 'Sheikh Khalifa Intern...","{'id': 2311, 'name': 'Mustapha Ghorbal', 'coun..."
4,3857255,2022-12-01,19:00:00.000,"{'competition_id': 43, 'country_name': 'Intern...","{'season_id': 106, 'season_name': '2022'}","{'home_team_id': 778, 'home_team_name': 'Japan...","{'away_team_id': 772, 'away_team_name': 'Spain...",2,1,available,available,2026-05-04T01:42:55.630428,2026-05-04T01:49:36.594944,"{'data_version': '1.1.0', 'shot_fidelity_versi...",3,"{'id': 10, 'name': 'Group Stage'}","{'id': 1000253, 'name': 'Sheikh Khalifa Intern...","{'id': 2366, 'name': 'Victor Miguel de Freitas..."

In [17]:
import json

with open(
    "../data/raw/statsbomb/data/lineups/3857276.json",
    encoding="utf-8"
) as f:
    lineup = json.load(f)

len(lineup)

2

In [18]:
lineup[0].keys()

dict_keys(['team_id', 'team_name', 'lineup'])

In [19]:
lineup[0]["team_name"]

'Morocco'

In [20]:
len(lineup[0]["lineup"])

26

In [21]:
lineup[0]["lineup"][0]

{'player_id': 3625,
 'player_name': 'Sofiane Boufal',
 'player_nickname': None,
 'jersey_number': 17,
 'country': {'id': 154, 'name': 'Morocco'},
 'cards': [],
 'positions': [{'position_id': 21,
   'position': 'Left Wing',
   'from': '00:00',
   'to': '64:10',
   'from_period': 1,
   'to_period': 2,
   'start_reason': 'Starting XI',
   'end_reason': 'Substitution - Off (Tactical)'}]}

In [22]:
for player in lineup[0]["lineup"]:
    if len(player["positions"]) > 1:
        print(player["player_name"])
        print(player["positions"])
        print()
        break

Romain Saïss
[{'position_id': 5, 'position': 'Left Center Back', 'from': '00:00', 'to': '76:14', 'from_period': 1, 'to_period': 2, 'start_reason': 'Starting XI', 'end_reason': 'Tactical Shift'}, {'position_id': 4, 'position': 'Center Back', 'from': '76:14', 'to': None, 'from_period': 2, 'to_period': None, 'start_reason': 'Tactical Shift', 'end_reason': 'Final Whistle'}]

In [23]:
with open(
    "../data/raw/statsbomb/data/events/3857276.json",
    encoding="utf-8"
) as f:
    events = json.load(f)

len(events)

3388

In [24]:

events[0].keys()

dict_keys(['id', 'index', 'period', 'timestamp', 'minute', 'second', 'type', 'possession', 'possession_team', 'play_pattern', 'team', 'duration', 'tactics'])

In [25]:
event_types = set()

for e in events:
    event_types.add(e["type"]["name"])

sorted(event_types)

['50/50',
 'Ball Receipt*',
 'Ball Recovery',
 'Block',
 'Carry',
 'Clearance',
 'Dispossessed',
 'Dribble',
 'Dribbled Past',
 'Duel',
 'Error',
 'Foul Committed',
 'Foul Won',
 'Goal Keeper',
 'Half End',
 'Half Start',
 'Injury Stoppage',
 'Interception',
 'Miscontrol',
 'Offside',
 'Own Goal Against',
 'Own Goal For',
 'Pass',
 'Pressure',
 'Referee Ball-Drop',
 'Shield',
 'Shot',
 'Starting XI',
 'Substitution',
 'Tactical Shift']

In [26]:
for e in events:
    if e["type"]["name"] == "Pass":
        print(e)
        break

{'id': '05a57281-9295-408a-9c4f-e32d7fad4d96', 'index': 5, 'period': 1, 'timestamp': '00:00:00.460', 'minute': 0, 'second': 0, 'type': {'id': 30, 'name': 'Pass'}, 'possession': 2, 'possession_team': {'id': 788, 'name': 'Morocco'}, 'play_pattern': {'id': 9, 'name': 'From Kick Off'}, 'team': {'id': 788, 'name': 'Morocco'}, 'player': {'id': 6301, 'name': 'Youssef En-Nesyri'}, 'position': {'id': 23, 'name': 'Center Forward'}, 'location': [61.0, 40.1], 'duration': 0.83469, 'related_events': ['1267faf9-e033-4985-925a-2f9521d63bc0'], 'pass': {'recipient': {'id': 5234, 'name': 'Sofyan Amrabat'}, 'length': 12.557467, 'angle': 3.045886, 'height': {'id': 1, 'name': 'Ground Pass'}, 'end_location': [48.5, 41.3], 'body_part': {'id': 38, 'name': 'Left Foot'}, 'type': {'id': 65, 'name': 'Kick Off'}}}