# Diseño

In [2]:
import pandas as pd
from pathlib import Path

BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()

processed_dir = BASE_DIR / "data" / "processed"

player_match_2018 = pd.read_csv(
    processed_dir / "player_vectors_2018_match_level.csv"
)

player_match_2022 = pd.read_csv(
    processed_dir / "player_vectors_2022_match_level.csv"
)

player_match = pd.concat(
    [player_match_2018, player_match_2022],
    ignore_index=True
)

player_match.shape

(3783, 29)

In [3]:
player_match.groupby(
    ["match_id", "team_name"]
)["player_id"].nunique().describe()

count    256.000000
mean      14.777344
std        1.077958
min       12.000000
25%       14.000000
50%       14.000000
75%       16.000000
max       17.000000
Name: player_id, dtype: float64

In [4]:
ID_COLS = [
    "player_id",
    "player_name",
    "team_name",
    "match_id",
]

feature_cols = [
    col for col in player_match.columns
    if col not in ID_COLS
]

team_vector_v01 = (
    player_match
    .groupby(["match_id", "team_name"], as_index=False)[feature_cols]
    .sum()
)

team_vector_v01.shape

(256, 27)

In [5]:
team_vector_v01.head()

,match_id,team_name,Ball Receipt*,Ball Recovery,Block,Carry,Clearance,Dispossessed,Dribble,Dribbled Past,...,Own Goal Against,Pass,Player Off,Player On,Pressure,Shot,Offside,Shield,Bad Behaviour,50/50
0,7525,Russia,339,52,16,269,9,19,12,4,...,0.0,388,0.0,0.0,147,14,0.0,0.0,0.0,3.0
1,7525,Saudi Arabia,527,49,22,440,16,13,11,9,...,0.0,572,0.0,0.0,121,6,0.0,0.0,0.0,3.0
2,7529,Croatia,484,34,14,399,22,6,10,12,...,0.0,503,1.0,1.0,160,11,0.0,1.0,0.0,0.0
3,7529,Nigeria,392,47,15,317,16,10,16,7,...,1.0,425,2.0,2.0,152,13,0.0,0.0,0.0,0.0
4,7530,Australia,415,48,16,345,19,13,5,14,...,1.0,444,0.0,0.0,113,5,0.0,0.0,0.0,1.0

In [6]:
team_vector_v01.columns.to_list()

['match_id',
 'team_name',
 'Ball Receipt*',
 'Ball Recovery',
 'Block',
 'Carry',
 'Clearance',
 'Dispossessed',
 'Dribble',
 'Dribbled Past',
 'Duel',
 'Error',
 'Foul Committed',
 'Foul Won',
 'Goal Keeper',
 'Interception',
 'Miscontrol',
 'Own Goal Against',
 'Pass',
 'Player Off',
 'Player On',
 'Pressure',
 'Shot',
 'Offside',
 'Shield',
 'Bad Behaviour',
 '50/50']

In [7]:
team_vector_v01.describe().T

,count,mean,std,min,25%,50%,75%,max
match_id,256.0,1.933994e+06,1.930077e+06,7525.0,7559.75,1932956.0,3857285.25,3869685.0
Ball Receipt*,256.0,4.789883e+02,1.548442e+02,187.0,364.50,471.5,572.00,1111.0
Ball Recovery,256.0,4.491797e+01,9.534926e+00,23.0,38.00,45.0,50.00,80.0
Block,256.0,1.775781e+01,6.034861e+00,3.0,14.00,17.0,21.00,35.0
Carry,256.0,4.073633e+02,1.438468e+02,143.0,302.00,400.0,490.25,943.0
Clearance,256.0,1.858203e+01,9.336472e+00,2.0,11.00,18.0,24.25,56.0
Dispossessed,256.0,1.023438e+01,4.531345e+00,2.0,7.00,10.0,13.00,26.0
Dribble,256.0,1.524219e+01,6.304988e+00,2.0,11.00,14.0,18.25,33.0
Dribbled Past,256.0,9.675781e+00,4.774150e+00,2.0,6.00,9.0,12.00,25.0
Duel,256.0,2.941406e+01,9.095163e+00,10.0,23.00,29.0,35.00,53.0
Error,256.0,2.539062e-01,4.870725e-01,0.0,0.00,0.0,0.00,2.0
Foul Committed,256.0,1.426172e+01,4.933068e+00,4.0,11.00,14.0,17.00,37.0
Foul Won,256.0,1.360156e+01,4.740877e+00,4.0,10.00,13.0,16.00,37.0
Goal Keeper,256.0,1.470703e+01,6.253792e+00,2.0,10.00,14.0,18.00,35.0
Interception,256.0,1.033984e+01,4.726825e+00,2.0,7.00,9.0,13.00,28.0
Miscontrol,256.0,1.285156e+01,4.290600e+00,2.0,10.00,12.0,16.00,27.0
Own Goal Against,256.0,5.859375e-02,2.353228e-01,0.0,0.00,0.0,0.00,1.0
Pass,256.0,5.132656e+02,1.556749e+02,224.0,399.25,509.5,605.00,1157.0
Player Off,256.0,5.351562e-01,7.610199e-01,0.0,0.00,0.0,1.00,4.0
Player On,256.0,5.351562e-01,7.610199e-01,0.0,0.00,0.0,1.00,4.0
Pressure,256.0,1.563086e+02,5.552271e+01,74.0,117.75,146.0,177.00,368.0
Shot,256.0,1.250000e+01,5.693478e+00,0.0,8.00,12.0,15.00,31.0
Offside,256.0,2.031250e-01,4.745999e-01,0.0,0.00,0.0,0.00,3.0
Shield,256.0,6.250000e-01,8.401681e-01,0.0,0.00,0.0,1.00,4.0
Bad Behaviour,256.0,3.281250e-01,8.175465e-01,0.0,0.00,0.0,0.00,8.0
50/50,256.0,1.343750e+00,1.606055e+00,0.0,0.00,1.0,2.00,9.0

Looks good. Guardo csv

In [8]:
team_vector_v01.to_csv(
    processed_dir / "team_vector_v01.csv",
    index=False
)